mysql_root_password: reverse
mysql_bind_address: '*'

mysql_users:
   - name: root
     host: 192.168.22.31
     password: reverse
     #     priv: *.*:USAGE

mysql_databases:
   - name: cv
     collation: utf8mb4_unicode_ci
     encoding: utf8mb4